Controllers/AdministrationController.cs
using fronk.Data;
using fronk.Extenstions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace fronk.Models
{
    /*[Authorize(Roles = "SYS_ADMIN")]*/
    /*[UserRoleAuthorize(UserRole.SYS_ADMIN)]*/
    public class AdministrationController : Controller
    {
        private readonly fronkContext _context;

        public AdministrationController(fronkContext context)
        {
            _context = context;
        }

        public IActionResult Users()
        {
            return RedirectToAction("Index", "Users");
            //return View("Index", "UsersController");
        }
        public IActionResult Statistics()
        {
            return View();
        }

        public List<User> Hello()
        {
            List<User> users = (from user in _context.User
                                select user).ToList();
            return users;
        }

        public JsonResult GetOrganizationsGroupedByCountry()
        {
            var query = from org in _context.Organization
                        group org by org.Country into country
                        select new
                        {
                            name = country.Key,
                            count = country.Count()
                        };

            List<Object> result = query.ToList<object>();

            return Json(result);
        }

        public JsonResult GetMostPopularEvents(int count)
        {
            count = count >= 1 ? count : 3;

            List<Event> events = _context.Event.Include(e => e.Users).ToList();

            IEnumerable<Object> result = events.Aggregate(new List<Object>(), (acc, cur) => {
                Object item = new
                {
                    title = cur.Title,
                    userCount = cur.Users.Count()
                };

                acc.Add(item);

                return acc;
            }).Take(count);

            return Json(result);
        }
    }
}

Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using fronk.Data;
using fronk.Models;
using fronk.Services;

namespace fronk.Controllers
{
    public class EventsController : Controller
    {
        private readonly fronkContext _context;
        private readonly UsersService _usersService;

        public EventsController(fronkContext context)
        {
            _context = context;
            _usersService = new UsersService(context);
        }

        public async Task<ActionResult> Search(
            int[]? categoryId, int[]? organizationId,
            string? date
            )
        {
            DateTime? parsedDate = date != null ? DateTime.Parse(date) : null;
            
            var query = from evnt in _context.Event
                where
                    (parsedDate == null ||
                     (evnt.Date.Day == parsedDate.Value.Day
                      && evnt.Date.Month == parsedDate.Value.Month
                      && evnt.Date.Year == parsedDate.Value.Year)) &&
                    (categoryId == null || categoryId.Length == 0 ||
                    categoryId.Contains(evnt.EventCategory.Id)) &&
                    (organizationId == null ||  organizationId.Length == 0 ||
                     organizationId.Contains(evnt.Organization.Id))
                select evnt;

            List<Event> events = await includeAllForeign(query).ToListAsync();

            ViewData["organizations"] = new MultiSelectList(_context.Organization,
                nameof(Organization.Id),
                nameof(Organization.Name), organizationId);
            ViewData["categories"] = new MultiSelectList(_context.EventCategory,
                nameof(EventCategory.Id),
                nameof(EventCategory.Name), categoryId);
            ViewData["date"] = date;

            return View(nameof(Index), events);
        }


        private IQueryable<Event> includeAllForeign(IQueryable<Event> query)
        {
            return query.Include(e => e.EventCategory)
                .Include(e => e.Location)
                .Include(e => e.Organization)
                .Include(e => e.Users);
        }

        private async Task<List<Event>> getAllEventsList()
        {
            return await includeAllForeign(_context.Event).ToListAsync();
        }

        public async Task<IActionResult> Index()
        {
            ViewData["organizations"] = new MultiSelectList(_context.Organization,
                nameof(Organization.Id),
                nameof(Organization.Name));
            ViewData["categories"] = new MultiSelectList(_context.EventCategory,
                nameof(EventCategory.Id),
                nameof(EventCategory.Name));

            return View(await getAllEventsList());
        }

        public async Task<IActionResult> SearchByTitle(string query)
        {
            query ??= "";

            var events = (
                from e in _context.Event
                join cat in _context.EventCategory
                    on e.EventCategoryId equals cat.Id
                join loc in _context.Location
                    on e.Id equals loc.EventId
                join org in _context.Organization
                    on e.OrganizationId equals org.Id
                where e.Title.Contains(query)
                select new
                {
                    id = e.Id,
                    date = e.Date,
                    title = e.Title,
                    description = e.Description,
                    imageSrc = e.ImageSrc,
                    catId = cat.Id,
                    catName = cat.Name,
                    catColor = cat.Color,
                    orgName = org.Name,
                    locName = loc.Name,
                    attendeesCount = e.Users.Count,
                    users = e.Users,
                }).ToList();

            return Json(events);
        }

        private List<User> addUsersAndGetList(Event e, User u)
        {
            List<User> users;
            if (e.Users == null)
            {
                users = new List<User>();
            }
            else
            {
                users = e.Users;
            }

            users.Add(u);

            return users;
        }

        private List<User> removeUserAndGetList(Event e, User u)
        {
            List<User> users = e.Users;
            if (users.Any(us => us.Id == u.Id))
            {
                users.Remove(u);
            }

            return users;
        }

        [HttpPost]
        public async Task<IActionResult> Join(int? eventId)
        {
            if (eventId == null || !EventExists((int) eventId))
            {
                return NotFound();
            }

            var currentUser = _usersService.getCurrentLoggedInUser(HttpContext);

            if (currentUser == null)
            {
                return Unauthorized();
            }

            var eventToJoin = await _context.Event
                .Include(e => e.Users)
                .FirstOrDefaultAsync(e => e.Id == eventId);
            List<User> updatedUsers = addUsersAndGetList(eventToJoin, currentUser);
            eventToJoin.Users = updatedUsers;

            if (ModelState.IsValid)
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View("Details", eventToJoin);
        }

        [HttpPost]
        public async Task<IActionResult> UnJoin(int? eventId)
        {
            var currentUser = _usersService.getCurrentLoggedInUser(HttpContext);

            if (currentUser == null)
            {
                return Unauthorized();
            }

            if (eventId == null || !EventExists((int) eventId))
            {
                return NotFound();
            }

            var eventToJoin = await _context.Event
                .Include(e => e.Users)
                .FirstOrDefaultAsync(e => e.Id == eventId);

            List<User> updatedUsers = removeUserAndGetList(eventToJoin, currentUser);
            eventToJoin.Users = updatedUsers;

            if (ModelState.IsValid)
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }

                return RedirectToAction(nameof(Index), await getAllEventsList());
            }

            return View("Details", eventToJoin);
        }

        public async Task<IActionResult> Category(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fronkContext =
                includeAllForeign(_context.Event.Where(e => e.EventCategoryId == id));

            ViewBag.CategoryView = true;
            return View("Index", await fronkContext.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await includeAllForeign(_context.Event)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        public async Task<IActionResult> Create()
        {
            var currentManager = _usersService.getCurrentLoggedInUser(HttpContext);
            bool isSysAdmin = currentManager.UserRole == UserRole.SYS_ADMIN;
            if (currentManager == null)
                return NotFound();

            Organization currentManagedOrg = currentManager.Organization;
            if (!isSysAdmin
                && (currentManagedOrg == null || currentManagedOrg.ManagerId != currentManager.Id))
                return Unauthorized();

            if (isSysAdmin)
            {
                ViewData["Orgs"] = new SelectList(_context.Organization,
                    nameof(Organization.Id),
                    nameof(Organization.Name));
                ViewData["EventCategoryId"] = new SelectList(_context.EventCategory, nameof(EventCategory.Id),
                    nameof(EventCategory.Name));
                return View();
            }

            Event model = new Event();
            model.OrganizationId = currentManagedOrg.Id;
            model.Organization = currentManagedOrg;
            model.CreatedAt = DateTime.Now;

            ViewData["Country"] = currentManagedOrg.Country;
            ViewData["OrgName"] = currentManagedOrg.Name;
            ViewData["EventCategoryId"] = new SelectList(_context.EventCategory, nameof(EventCategory.Id),
                nameof(EventCategory.Name));
            return View(model);
        }

        // POST: Events/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,OrganizationId,Title,Description,EventCategoryId,CreatedAt,Date,ImageSrc")]
            Event @event, string placeId, string placeName)
        {
            var currentUser = _usersService.getCurrentLoggedInUser(HttpContext);
            bool validLocationFields = placeId != null && placeName != null;

            if (currentUser == null)
            {
                return Unauthorized();
            }
            
            if (validLocationFields)
                addLocationAndUpdateEvent(@event, placeId, placeName);

            ModelState.Remove("Location");

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using fronk.Data;
using fronk.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;

namespace fronk.Controllers
{
    public class LoginController : Controller
    {
        private readonly fronkContext _context;

        public LoginController(fronkContext context)
        {
            _context = context;
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("Id,Name,Email,Password,UserRole,CreatedAt")] User user)
        {
            if (ModelState.IsValid)
            {
                User foundUser = _context.User.FirstOrDefault(u => u.Name == user.Name && u.Password == user.Password);

                if (foundUser == null)
                {
                    ViewData["ErrorMessage"] = "Oysh, you are missing something...";
                }
                else
                {
                    this.Signin(foundUser);
                    return RedirectToAction(nameof(Index), "Home");
                }
            }

            return View(user);
        }

        private Boolean checkCredentails(string username, string password)
        {
            var matchingUsers = _context.User.Where(user => user.Name == username && user.Password == password);

            return (matchingUsers.Count() == 1);
        }

        private async void Signin(User user)
        {
            List<Claim> claims = new List<Claim> { 
                new Claim(ClaimTypes.Name, user.Name),
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                new Claim(ClaimTypes.Role, user.UserRole.ToString())
            };
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            AuthenticationProperties authProperties = new AuthenticationProperties {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10)
            };
            
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity),authProperties);
        }

        public IActionResult Register()
        {
            ViewData["Gender"] = new SelectList(Enum.GetValues(typeof(Gender)));

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([Bind("Id,Name,Email,Password,UserRole,CreatedAt")] User user)
        {
            if (ModelState.IsValid)
            {
                if (isUsernameTaken(user.Name))
                {
                    ViewData["ErrorMessage"] = "Oops... You'll have to be more creative!";
                }
                else
                {
                    user.UserRole = UserRole.CLIENT;
                    user.CreatedAt = new DateTime();

                    _context.Add(user);
                    await _context.SaveChangesAsync();

                    this.Signin(user);

                    return RedirectToAction(nameof(Index), "Home");
                }
            }

            return View(user);
        }


        private Boolean isUsernameTaken(string username) 
        {
            User existingUser = this._context.User.FirstOrDefault(user => user.Name == username);
            return existingUser != null;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - fronk</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/organizations.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">fronk</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link nav-part" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-part" asp-area="" asp-controller="Organizations" asp-action="Index">Explore Organizations</a>
                        </li>
                        @if (Context.User != null && Context.User.Claims != null && Context.User.Claims.Count() > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link nav-part" asp-area="" asp-controller="Organizations" asp-action="MyOrganization">My Organization</a>
                            </li>
                        }
                            <li class="nav-item">
                                <a class="nav-link nav-part" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                            </li>

                            @if (Context.User.Claims.FirstOrDefault(claim => claim.Type.Contains("Role", StringComparison.OrdinalIgnoreCase)) != null &&
                            Context.User.Claims.FirstOrDefault(claim => claim.Type.Contains("Role", StringComparison.OrdinalIgnoreCase)).Value == UserRole.SYS_ADMIN.ToString())
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Administration
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <li><a asp-controller="Administration" asp-action="Statistics">Statistics</a></li>
                                        <li><a asp-controller="Administration" asp-action="Users">Users</a></li>
                                        <li><a asp-controller="EventCategories" asp-action="Index">Event Categories</a></li>
                                    </ul>
                                </li>
                            }


                            @if (Context.User != null && Context.User.Claims != null && Context.User.Claims.Count() > 0)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                </li>

                                <div>
                                    Hi @Context.User.Identity.Name
                                </div>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                                </li>
                            }
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
@*<script src="~/lib/jquery/dist/jquery.js"></script>*@
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://d3js.org/d3.v7.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/react-dot-net.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - fronk</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - fronk - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>