Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using fronk.Data;
using fronk.Models;
using fronk.Services;
using Microsoft.AspNetCore.Authorization;

namespace fronk.Controllers
{
    public class OrgnizationForUser
    {
        public IEnumerable<Organization> Owned { get; set; }

        public IEnumerable<Organization> Follwing { get; set; }

        public IEnumerable<Organization> Others { get; set; }

    }

    public class OrganizationsController : Controller
    {
        private readonly fronkContext _context;
        private readonly UsersService _usersService;

        public OrganizationsController(fronkContext context)
        {
            _context = context;
            _usersService = new UsersService(context);
        }

        public async Task<OrgnizationForUser> GetUserOrgs()
        {
            User curUser = _usersService.getCurrentLoggedInUser(HttpContext);
            IEnumerable<Organization> Owned = await _context.Organization.Where(org => curUser != null && org.Manager.Id == curUser.Id).ToListAsync();
            IEnumerable<Organization> Joined = await getJoinedOrganizations();
            IEnumerable<Organization> Unjoined = await getUnJoinedOrganizations();
            OrgnizationForUser result = new OrgnizationForUser
            {
                Owned = Owned,
                Follwing = Joined,
                Others = Unjoined
            };

            return result;
        }

        public async Task<IEnumerable<Organization>> getJoinedOrganizations()
        {
            int? curUserId = _usersService.getCurrentLoggedInUserId(HttpContext);
            IEnumerable<Organization> organizations = new List<Organization>();

            if (curUserId != null)
            {
                var fronkContext = _context.Organization
                .Include(o => o.Manager)
                .Include(o => o.UserOrganizations)
                .ThenInclude(uo => uo.User)
                .Where(org => org.UserOrganizations.Any(uo => uo.UserId == curUserId));

                organizations = await fronkContext.ToListAsync();
            }

            return organizations;
        }

        public async Task<IEnumerable<Organization>> getUnJoinedOrganizations()
        {
            int? curUserId = _usersService.getCurrentLoggedInUserId(HttpContext);
            IEnumerable<Organization> organizations = new List<Organization>();

            if (curUserId != null)
            {
                var fronkContext = _context.Organization
                    .Include(o => o.Manager)
                    .Include(o => o.UserOrganizations)
                    .ThenInclude(uo => uo.User)
                     .Where(org => org.ManagerId != curUserId && (org.UserOrganizations.Count() == 0 || org.UserOrganizations.All(uo => uo.UserId != curUserId)));

                organizations = await fronkContext.ToListAsync();
            }
            return organizations;
        }

        public async Task<IActionResult> Index()
        {
            var fronkContext = _context.Organization
                .Include(o => o.Manager)
                .Include(o => o.UserOrganizations)
                .ThenInclude(uo => uo.User);
            List<Organization> organizations = await fronkContext.ToListAsync();
            OrgnizationForUser orgs = await GetUserOrgs();

            return View(orgs);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.Organization
                .Include(o => o.Manager)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }

            return View(organization);
        }

        public IActionResult Create()
        {
            var currentUser = _usersService.getCurrentLoggedInUser(HttpContext);

            Organization org = new Organization();
            org.Manager = currentUser;
            org.ManagerId = currentUser.Id;

            return View(org);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Country,Video,Description,ManagerId")] Organization organization)
        {
            var currentUser = _usersService.getCurrentLoggedInUser(HttpContext);
            if (currentUser.UserRole == UserRole.ORG_ADMIN)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                if(currentUser.UserRole == UserRole.CLIENT)
                    currentUser.UserRole = UserRole.ORG_ADMIN;
                currentUser.OrganizationId = organization.Id;
                currentUser.Organization = organization;

                _context.Add(organization);
                _context.Update(currentUser);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            
            organization.Manager = currentUser;
            organization.ManagerId = currentUser.Id;
            return View(organization);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.Organization.FindAsync(id);
            if (organization == null)
            {
                return NotFound();
            }


            return View(organization);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Country,Video,Description,ManagerId")] Organization organization)
        {
            if (id != organization.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(organization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrganizationExists(organization.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(organization);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.Organization
                .Include(o => o.Manager)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }

            return View(organization);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var organization = await _context.Organization.FindAsync(id);
            _context.Organization.Remove(organization);

            var currentUser = _usersService.getCurrentLoggedInUser(HttpContext);
            if(currentUser.UserRole == UserRole.ORG_ADMIN)
                currentUser.UserRole = UserRole.CLIENT;
            
            _context.Update(currentUser);
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrganizationExists(int id)
        {
            return _context.Organization.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Search(string? name, string? country)
        {
            var query = from organization in _context.Organization
                        where (name != null ? organization.Name.ToLower().Contains(name.ToLower()) : true) &&
                              (country != null ? organization.Country.ToLower() == country.ToLower() : true)
                        select organization;

            List<Organization> foundOrganizations = await query.Include(o => o.Manager)
                                                                .Include(o => o.UserOrganizations)
                                                                .ThenInclude(uo => uo.User).ToListAsync();
            
            int? curUserId = _usersService.getCurrentLoggedInUserId(HttpContext);

            OrgnizationForUser searchResult = new OrgnizationForUser
            {
                Follwing = foundOrganizations.Where(org => org.UserOrganizations.Any(uo => uo.UserId == curUserId)),
                Others = foundOrganizations.Where(org => org.ManagerId != curUserId && (org.UserOrganizations.Count() == 0 || org.UserOrganizations.All(uo => uo.UserId != curUserId)))
            };

            ViewData["SearchedName"] = name;
            ViewData["SearchedCountry"] = country;

            return View("Index", searchResult);
        }
        
        [HttpPost]
        public async Task<IActionResult> Join(int? orgId)
        {
            if (orgId == null || !OrganizationExists((int) orgId))
            {
                return NotFound();
            }

            var currentUser = _usersService.getCurrentLoggedInUserExtendedIncludes(HttpContext);

            if (currentUser == null 
                || currentUser.UserOrganizations.Any(org => org.OrganizationId == orgId))
            {
                return Unauthorized();
            }

            var orgToJoin = await _context.Organization
                .Include(e => e.UserOrganizations)

Views/Organizations/Create.cshtml
@model fronk.Models.Organization

@{
    ViewData["Title"] = "Create";
}

<head>
    <style>
        body {
            background: -webkit-linear-gradient(left, #0072ff, #00c6ff);
        }

        .contact-form {
            background: #fff;
            margin-top: 10%;
            margin-bottom: 5%;
            width: 90%;
        }

            .contact-form .form-control {
                border-radius: 1rem;
            }

        .contact-image {
            text-align: center;
        }

            .contact-image img {
                border-radius: 6rem;
                width: 11%;
                margin-top: -3%;
            }

        .contact-form form {
            padding: 14%;
        }

            .contact-form form .row {
                margin-bottom: -7%;
            }

        .contact-form h3 {
            margin-bottom: 8%;
            margin-top: -10%;
            text-align: center;
            color: #0062cc;
        }

        .contact-form .btnContact {
            width: 100%;
            border: none;
            border-radius: 1rem;
            padding: 1.5%;
            background: #42db47;
            font-weight: 600;
            color: #fff;
            cursor: pointer;
        }

        .btnContactSubmit {
            width: 50%;
            border-radius: 1rem;
            padding: 1.5%;
            color: #fff; 
            background-color: #0062cc;
            border: none;
            cursor: pointer;
        }
    </style>
</head>

<body>
    <div class="container contact-form">
        <div class="contact-image">
            <img src="https://freeiconshop.com/wp-content/uploads/edd/plus-flat.png" alt="rocket_contact" />
        </div>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" type="text" class="form-control" placeholder="Organization's name" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Country" class="control-label"></label>
                        <input asp-for="Country" class="form-control" placeholder="Country code" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Video" class="control-label"></label>
                        <input asp-for="Video" class="form-control" placeholder="Video URL" />
                        <span asp-validation-for="Video" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="btnSubmit" class="btnContact btn btn-primary" value="Create" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" placeholder="Write a few words describing your org" style="width: 100%; height: 235px;" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Organizations/Delete.cshtml
@model fronk.Models.Organization

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Organization</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Video)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Video)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manager.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Organizations/Edit.cshtml
@model fronk.Models.Organization

@{
    ViewData["Title"] = "Edit";
}

<head>
    <style>
        body {
            background: -webkit-linear-gradient(left, #0072ff, #00c6ff);
        }

        .contact-form {
            background: #fff;
            margin-top: 10%;
            margin-bottom: 5%;
            width: 90%;
        }

            .contact-form .form-control {
                border-radius: 1rem;
            }

        .contact-image {
            text-align: center;
        }

            .contact-image img {
                border-radius: 6rem;
                width: 11%;
                margin-top: -3%;
            }

        .contact-form form {
            padding: 14%;
        }

            .contact-form form .row {
                margin-bottom: -7%;
            }

        .contact-form h3 {
            margin-bottom: 8%;
            margin-top: -10%;
            text-align: center;
            color: #0062cc;
        }

        .contact-form .btnContact {
            width: 100%;
            border: none;
            border-radius: 1rem;
            padding: 1.5%;
            background: #42db47;
            font-weight: 600;
            color: #fff;
            cursor: pointer;
        }

        .btnContactSubmit {
            width: 50%;
            border-radius: 1rem;
            padding: 1.5%;
            color: #fff;
            background-color: #0062cc;
            border: none;
            cursor: pointer;
        }
    </style>
</head>

<body>
    <div class="container contact-form">
        <div class="contact-image">
            <img src="https://freeiconshop.com/wp-content/uploads/edd/plus-flat.png" alt="rocket_contact" />
        </div>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" type="text" class="form-control" placeholder="Organization's name" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Country" class="control-label"></label>
                        <input asp-for="Country" class="form-control" placeholder="Country code" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Video" class="control-label"></label>
                        <input asp-for="Video" class="form-control" placeholder="Video URL" />
                        <span asp-validation-for="Video" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="btnSubmit" class="btnContact btn btn-primary" value="Save" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" placeholder="Write a few words describing your org" style="width: 100%; height: 235px;" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </form>
    </div>
</body>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Organizations/Index.cshtml
@using System.Security.Claims;

@model fronk.Controllers.OrgnizationForUser

@{
    ViewData["Title"] = "Index";
}

@section Scripts {
    <script src="~/js/Orgs.js"></script>
}

<head>
    <style>
        #memberBadge:hover span {
            display: none
        }

        #memberBadge:hover:before {
            content: "Remove";
        }
    </style>
</head>

<div class="container org-page-section">
    <div class="row org-page-section-content">
        <div class="col-6">
            @if (Context.User.FindFirst(ClaimTypes.Role) != null
               && Context.User.FindFirst(ClaimTypes.Role).Value != UserRole.ORG_ADMIN.ToString())
            {
                <a class="btn btn-primary" asp-action="Create">Create New</a>
            }
        </div>
        <div class="col-6">
            <form asp-controller="Organizations" asp-action="Search" class="form-horizontal">
                <div class="row">
                    <div class="col-8">
                        <div class="form-group">
                            <input id="name" name="name" class="form-control" placeholder="org name goes here" value="@ViewBag.SearchedName" />
                        </div>
                    </div>
                    <div class="col-2">
                        <div>
                            <input type="submit" value="Search" class="btn btn-outline-primary" />
                        </div>
                    </div>
                    <div class="col-2">
                        <a role="button" class="btn btn-outline-info" asp-action="Index">Clear</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8"></div>
                    <div class="col-4" id="orgAdvancedSearchOptionsToggler"><small>Advanced Search</small></div>
                </div>
                <div class="row hidden" id="orgAdvancedSearchOptions">
                    <div class="col-8">
                        <div class="form-group">
                            <input id="country" name="country" class="form-control" placeholder="country code" value="@ViewBag.SearchedCountry" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
@*<div class="org-page-section">
    <div class="org-page-section-title">
        <h3>My organization</h3>
    </div>
    <div class="org-page-section-content">
        @if (Model.Owned.Count() == 0)
        {
            <div>What are you waiting for?</div>
            <div>Start </div>
            @if (Context.User.FindFirst(ClaimTypes.Role) != null
              && Context.User.FindFirst(ClaimTypes.Role).Value != UserRole.ORG_ADMIN.ToString())
            {
                <a class="btn btn-primary" asp-action="Create">Create New</a>
            }
        }
        else
        {
            @foreach (var item in Model.Owned)
            {
                <a asp-action="Details" asp-route-id="@item.Id" class="list-group-item list-group-item-action flex-column align-items-start org-list-item">
                    <div class="d-flex w-100 justify-content-between">
                        <div style="flex: 1">
                            <h5 class="mb-1">@item.Name</h5>
                        </div>
                        <div class="mb-1" style="flex: 3; overflow: hidden; text-overflow: ellipsis; text-align: center; white-space: nowrap;">
                            @item.Description
                        </div>
                        <div style="flex: 1;float: right;display: flex;flex-direction: row-reverse;">
                            @if (
Context.User.Identity.IsAuthenticated
&& @item.ManagerId.ToString() != Context.User.FindFirst(ClaimTypes.NameIdentifier)?.Value.ToString()
)
                            {
                                bool attending = (
                                    @item.UserOrganizations
                                        .Any(uo =>
                                            uo.User.Id.ToString() ==
                                            Context.User.FindFirst(ClaimTypes.NameIdentifier)?.Value
                                        )
                                    );

                                @if (attending)
                                {
                                    <button class="btn btn-outline-info" id="memberBadge" onclick="unjoinOrg(event, @item.Id)">
                                        <span>
                                            Member
                                        </span>
                                    </button>
                                }
                                else
                                {
                                    <button id="joinButton"
                                            type="button" class="btn btn-outline-info"
                                            onclick="joinOrg(event, @item.Id)">
                                        Join
                                    </button>
                                }
                            }
                        </div>
                    </div>
                </a>
            }
        }
    </div>
</div>*@

    <div class="org-page-section">
        <div class="org-page-section-title">
            <h3>Follwed Organizations</h3>
        </div>
        <div class="org-page-section-content" id="joinedOrgs">
            @if (Model.Follwing.Count() == 0)
            {
            <div>
                <p>
                    It's seems like you are not that active...
                </p>
                <p>
                    Don't be shy, scroll down and start explore new adventures!!
                </p>
            </div>
            }
            else
            {
            @foreach (var item in Model.Follwing)
            {
                    <a asp-action="Details" asp-route-id="@item.Id" class="list-group-item list-group-item-action flex-column align-items-start org-list-item">
                        <div class="d-flex w-100 justify-content-between">
                            <div style="flex: 1">
                                <h5 class="mb-1">@item.Name</h5>
                            </div>
                            <div class="mb-1" style="flex: 3; overflow: hidden; text-overflow: ellipsis; text-align: center; white-space: nowrap;">
                                @item.Description
                            </div>
                            <div style="flex: 1;float: right;display: flex;flex-direction: row-reverse;">
                                @if (
Context.User.Identity.IsAuthenticated
&& @item.ManagerId.ToString() != Context.User.FindFirst(ClaimTypes.NameIdentifier)?.Value.ToString()
)
                                {
                                    bool attending = (
                                        @item.UserOrganizations
                                            .Any(uo =>
                                                uo.User.Id.ToString() ==
                                                Context.User.FindFirst(ClaimTypes.NameIdentifier)?.Value
                                            )
                                        );

                                    @if (attending)
                                    {
                                        <button class="btn btn-outline-info" id="memberBadge" onclick="unjoinOrg(event, @item.Id)">
                                            <span>
                                                Member
                                            </span>
                                        </button>
                                    }
                                    else
                                    {
                                        <button id="joinButton"
                                                type="button" class="btn btn-outline-info"
                                                onclick="joinOrg(event, @item.Id)">
                                            Join
                                        </button>
                                    }
                                }
                            </div>
                        </div>
                    </a>
            }
            }
        </div>
    </div>

    <div class="org-page-section">
        <div class="org-page-section-title row">
            <h3>Explore Organizations</h3>
        </div>
        <div class="org-page-section-content" id="unjoinedOrgs">
            
            @if (Model.Others.Count() == 0)
            {
                <div>
                    THERE ARE NO ORGS FOR YOU TO EXPLORE... SAD.
                </div>
            }
            else
            {
                <div class="list-group">
                    @foreach (var item in Model.Others)
                    {
                        <a asp-action="Details" asp-route-id="@item.Id" class="list-group-item list-group-item-action flex-column align-items-start org-list-item">
                            <div class="d-flex w-100 justify-content-between">
                                <div style="flex: 1">
                                    <h5 class="mb-1">@item.Name</h5>
                                </div>
                                <div class="mb-1" style="flex: 3; overflow: hidden; text-overflow: ellipsis; text-align: center; white-space: nowrap;">
                                    @item.Description
                                </div>
                                <div style="flex: 1;float: right;display: flex;flex-direction: row-reverse;">
                                    @if (
Context.User.Identity.IsAuthenticated
&& @item.ManagerId.ToString() != Context.User.FindFirst(ClaimTypes.NameIdentifier)?.Value.ToString()
)
                                    {
                                        bool attending = (
                                            @item.UserOrganizations
                                                .Any(uo =>
                                                    uo.User.Id.ToString() ==
                                                    Context.User.FindFirst(ClaimTypes.NameIdentifier)?.Value
                                                )
                                            );

                                        @if (attending)
                                        {
                                            <button class="btn btn-outline-info" id="memberBadge" onclick="unjoinOrg(event, @item.Id)">
                                                <span>
                                                    Member
                                                </span>
                                            </button>
                                        }
                                        else
                                        {
                                            <button id="joinButton"
                                                    type="button" class="btn btn-outline-info"
                                                    onclick="joinOrg(event, @item.Id)">
                                                Join
                                            </button>
                                        }
                                    }
                                </div>
                            </div>
                        </a>
                    }
                </div>
            }
        </div>
    </div>
    
    

</div>